import os
import tempfile
import unittest
from pathlib import Path

from gmx_harness import GroAtom, GroFile, Layout, MoleculeLabels, PreprocessError, preprocess, preprocess_file
from gmx_harness.plumed import compress

MOL = MoleculeLabels(("A", "A", "B", "B"), ("C1", "H1", "N1", "H2"))
LAY = Layout(MOL, nmol=4, nros=2)

USAGE = Path(__file__).resolve().parents[2] / "usage"


def body(text: str) -> list[str]:
    return text.splitlines()[1:]  # drop the "# generated by ..." header


class TestSelection(unittest.TestCase):
    def test_sel(self) -> None:
        self.assertEqual(LAY.sel(res="A"), "1-2,5-6,9-10,13-14")
        self.assertEqual(LAY.sel(disk=1, mol=0, res="B", heavy=True), "11")
        self.assertEqual(LAY.sel(disk=0, res="A,B"), "1-8")
        self.assertEqual(LAY.sel(name=["H1", "H2"]), "2,4,6,8,10,12,14,16")
        self.assertEqual(Layout(MOL, nmol=2, nros=2, offset=100).sel(mol=1, res="A"), "105-106")

    def test_compress(self) -> None:
        self.assertEqual(compress([1, 2, 3, 7, 9, 10]), "1-3,7,9-10")
        self.assertEqual(compress([]), "")

    def test_unknown_or_empty_selection(self) -> None:
        for kw in ({"res": "Z"}, {"disk": 5}, {"mol": 2}, {"name": "X9"}):
            with self.assertRaises(PreprocessError, msg=str(kw)):
                LAY.sel(**kw)
        with self.assertRaises(PreprocessError):
            Layout(MoleculeLabels(("A",), ("H1",)), 1, 1).sel(heavy=True)

    def test_labels_from_gro(self) -> None:
        gro = GroFile("t", [GroAtom(1, "C1", "BAR", 1, [0, 0, 0]), GroAtom(2, "H1", "PNP", 1, [0, 0, 0])], 1, 1, 1)
        from_obj = MoleculeLabels.from_grofile(gro)
        with tempfile.TemporaryDirectory() as d:
            p = os.path.join(d, "m.gro")
            gro.save_gro(p)
            self.assertEqual(MoleculeLabels.from_gro(p), from_obj)
        self.assertEqual(from_obj, MoleculeLabels(("BAR", "PNP"), ("C1", "H1")))


class TestPreprocess(unittest.TestCase):
    def test_directives(self) -> None:
        tpl = """#define N 2
# for a plain comment
#for k in 0..N-1
#for i in 0..1
m{k}_{i}: COM ATOMS=@sel(disk=k, mol=i, res="A")
#endfor
t{k}: X ARG={join("m%d_{i}" % k, 2)} NEXT={k+1} LIT={{x}}
#endfor
"""
        self.assertEqual(body(preprocess(tpl, LAY)), [
            "# for a plain comment",
            "m0_0: COM ATOMS=1-2", "m0_1: COM ATOMS=5-6", "t0: X ARG=m0_0,m0_1 NEXT=1 LIT={x}",
            "m1_0: COM ATOMS=9-10", "m1_1: COM ATOMS=13-14", "t1: X ARG=m1_0,m1_1 NEXT=2 LIT={x}",
        ])

    def test_defines_override_template(self) -> None:
        self.assertEqual(body(preprocess("#define N 2\nv={N}", LAY, {"N": 5})), ["v=5"])

    def test_helpers(self) -> None:
        self.assertEqual(body(preprocess("x=@twice(3)", LAY, helpers={"twice": lambda v: 2 * v})), ["x=6"])

    def test_errors(self) -> None:
        for bad in ('@sel(res="Z")', "{nope}", "#for k in 0..1", "#endfor", "{1 +}", "x }", "#define 1bad 2"):
            with self.assertRaises(PreprocessError, msg=bad):
                preprocess(bad, LAY)

    def test_include_is_confined(self) -> None:
        with tempfile.TemporaryDirectory() as d:
            root = Path(d, "tpl")
            (root / "parts").mkdir(parents=True)
            (root / "parts" / "com.inc").write_text("c: COM ATOMS=@sel(res=\"B\", disk=0)\n")
            Path(d, "secret.inc").write_text("leaked\n")
            (root / "ok.in").write_text('#include "parts/com.inc"\n')
            (root / "bad.in").write_text('#include "../secret.inc"\n')
            self.assertEqual(body(preprocess_file(root / "ok.in", LAY)), ["c: COM ATOMS=3-4,7-8"])
            with self.assertRaises(PreprocessError):
                preprocess_file(root / "bad.in", LAY)


class TestSandbox(unittest.TestCase):
    def test_python_internals_are_unreachable(self) -> None:
        for bad in (
            "{().__class__}",
            "{().__class__.__base__.__subclasses__()}",
            "@__import__('os')",
            "{(lambda: 1)()}",
            "{open('x')}",
            "{_secret}",
            "{sel.__globals__}",
        ):
            with self.assertRaises(PreprocessError, msg=bad):
                preprocess(bad, LAY)
        with self.assertRaises(PreprocessError):
            preprocess("x", LAY, {"__builtins__": {}})


@unittest.skipUnless((USAGE / "3md_planning/plumed/metad_twist.plumed.in").exists(), "usage workspace not present")
class TestRealTemplate(unittest.TestCase):
    """The template, labeled gro and settings of the real WT-MetaD run in the usage workspace."""

    def test_reproduces_the_deployed_plumed_dat(self) -> None:
        layout = Layout(MoleculeLabels.from_gro(USAGE / "resource/gro/BarPNPOMeTDPChiral_gaff2_labeled.gro"),
                        nmol=60, nros=6)
        defines = dict(NDISK=10, NROS=6, CORE="BAR,CHL,PNP", SIGN=1, BIAS_IFACE=4, PRINT_STRIDE=500,
                       SIGMA=0.035, HEIGHT=1.2, PACE=500, BIASFACTOR=15, TEMP=300, GRID_BIN=240)
        text = preprocess_file(USAGE / "3md_planning/plumed/metad_twist.plumed.in", layout, defines)
        # plumed_pp named the source by the path it was given; compare everything after the header line
        expected = (USAGE / "resource/plumed/BarPNPOMeTDPChiral_gaff2_stack10_metad.dat").read_bytes().decode()
        self.assertEqual(body(text), body(expected.replace("\r\n", "\n")))


if __name__ == "__main__":
    unittest.main()
