"""Generate the LLM-facing API reference (Markdown) from ``__all__`` and docstrings.

No third-party dependency: signatures come from ``inspect``, prose from the
docstrings, so keeping docstrings accurate keeps the agent docs accurate.
"""

import dataclasses
import enum
import importlib
import inspect
from pathlib import Path
from types import ModuleType
from typing import Any

# (module, names or None for the module's __all__, heading)
_SECTIONS: list[tuple[str, list[str] | None, str]] = [
    ("gmx_harness", None, "gmx_harness"),
    ("gmx_harness.relax", ["relax", "parse_inter_bonds", "find_inter_itp", "write_gro"],
     "gmx_harness.relax"),
    ("gmx_harness.analysis", ["Recorder", "analyze_trj", "process_files", "generate_excel", "mixing_recorders",
                              "get_calcname", "make_analyze_command_script"], "gmx_harness.analysis"),
]


def _doc(obj: Any) -> str:
    return inspect.getdoc(obj) or ""


def _sig(obj: Any) -> str:
    try:
        return str(inspect.signature(obj))
    except (TypeError, ValueError):
        return "(...)"


def _describe(name: str, obj: Any) -> list[str]:
    out: list[str] = []
    if inspect.isclass(obj) and issubclass(obj, enum.Enum):
        out.append(f"### enum `{name}`")
        out.append(", ".join(f"`{m.name}`" for m in obj))
    elif inspect.isclass(obj):
        base = ", ".join(b.__name__ for b in obj.__bases__ if b is not object)
        out.append(f"### class `{name}{_sig(obj)}`" + (f"  (bases: {base})" if base else ""))
        if _doc(obj):
            out.append(_doc(obj))
        if dataclasses.is_dataclass(obj):
            rows = []
            for f in dataclasses.fields(obj):
                t = f.type if isinstance(f.type, str) else getattr(f.type, "__name__", str(f.type))
                if f.default is not dataclasses.MISSING:
                    default = repr(f.default)
                elif f.default_factory is not dataclasses.MISSING:
                    default = repr(f.default_factory())
                else:
                    default = "required"
                rows.append(f"| `{f.name}` | `{t}` | `{default}` |")
            if rows:
                out += ["", "| field | type | default |", "|---|---|---|", *rows]
        methods = []
        for mname, member in obj.__dict__.items():
            if mname.startswith("_"):
                continue
            fn = member.__func__ if isinstance(member, (classmethod, staticmethod)) else member
            if isinstance(member, property):
                methods.append(f"- property `{mname}` - {(_doc(member).splitlines() or [''])[0]}")
            elif inspect.isfunction(fn):
                first = (_doc(fn).splitlines() or [""])[0]
                kind = "classmethod " if isinstance(member, classmethod) else ""
                methods.append(f"- {kind}`{mname}{_sig(fn)}` - {first}")
        if methods:
            out += ["", "Methods:", *methods]
    elif callable(obj):
        out.append(f"### `{name}{_sig(obj)}`")
        if _doc(obj):
            out.append(_doc(obj))
    else:
        out.append(f"### `{name}` = `{obj!r}`")
    return out


def generate_api_markdown() -> str:
    lines = [
        "# gmx_harness API reference (for AI agents)",
        "",
        "Generated by `gmx_harness.apidoc.write_api_docs()` from the docstrings. Do not edit by hand.",
        "",
        "Ground rules: gmx_harness only *writes* files and bash scripts; it never runs GROMACS. "
        "Build a plan with `build_plan`, show `plan.preview()`, then `plan.write()`. "
        "Anything that needs `allow_unsafe=True` or `confirm=True` must be approved by the human.",
    ]
    for module_name, names, heading in _SECTIONS:
        try:
            mod: ModuleType = importlib.import_module(module_name)
        except ImportError as e:
            lines += ["", f"## {heading}", "", f"_(not documented: {e})_"]
            continue
        lines += ["", f"## {heading}"]
        if mod.__doc__ and names is None:
            lines += ["", inspect.cleandoc(mod.__doc__)]
        for name in names if names is not None else list(getattr(mod, "__all__", [])):
            if name.startswith("__"):
                continue
            lines += [""] + _describe(name, getattr(mod, name))
    return "\n".join(lines) + "\n"


def bundled_api_docs_path() -> Path:
    return Path(__file__).parent / "harness" / "llm_docs" / "api.md"


def write_api_docs(path: str | Path | None = None) -> Path:
    """Regenerate the API reference (default: the bundled ``harness/llm_docs/api.md``). Returns the path."""
    out = Path(path) if path is not None else bundled_api_docs_path()
    out.write_text(generate_api_markdown(), encoding="utf-8", newline="\n")
    return out
